# Configurations
title:            主页
longtitle:        主页
author:           YooyoJin
email:            yooyojin@foxmail.com
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

url:              'https://yooyojin.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   4

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 1000px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

# 本页未使用远程主题，通过fork下来自定义主题，若使用远程主题需要增加插件
# plugins:
#   - jekyll-remote-theme